export const actionTypes = {
  getMeal:'FETCH_FOOD',
  logIn: 'LOG_IN',
  signUp: 'SIGN_UP',
  addToCart: 'ADD_TO_CART',
  CHECK_OUT: 'CHECK_OUT',
  ORDER_HISTORY: 'ORDER_HISTORY',
  ORDER_HISTORY_ERROR: 'ORDER_HISTORY_ERROR',
  DELETE_ORDER: 'DELETE_ORDER',
  DELETE_ORDER_ERROR: 'DELETE_ORDER_ERROR',
  DELETE_ORDER_SUCSESS: 'DELETE_ORDER_SUCSESS',
}